// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseNode: typeof import('./src/components/BaseNode/index.ts')['default']
    DeltaNode: typeof import('./src/components/DeltaNode/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElLink: typeof import('element-plus/es')['ElLink']
    EllipseNode: typeof import('./src/components/EllipseNode/index.vue')['default']
    ElMain: typeof import('element-plus/es')['ElMain']
    RoundRectNode: typeof import('./src/components/RoundRectNode/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
